package com.ssm.entity;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_.id
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_.name
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_.id
     *
     * @return the value of category_.id
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_.id
     *
     * @param id the value for category_.id
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_.name
     *
     * @return the value of category_.name
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_.name
     *
     * @param name the value for category_.name
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}