package com.ssm.dao;

import com.ssm.entity.Category;
import com.ssm.entity.CategoryExample;
import java.util.List;

import com.ssm.util.Page;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

@MapperScan()
public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    int countByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    int deleteByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    List<Category> selectByExample();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    int updateByExample(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_
     *
     * @mbggenerated Wed Nov 22 09:51:48 CST 2017
     */
    int updateByPrimaryKey(Category category);

    public List<Category> list();

    public int total();

    int add(Category category);
    public void delete(int id);
    public Category get(int id);
    //  int deleteBookById(long id);
    //  int add(Category category);
}